# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(560, 572)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_5 = QtWidgets.QPushButton(Dialog)
        self.btn_5.setObjectName("btn_5")
        self.horizontalLayout.addWidget(self.btn_5)
        self.btn_4 = QtWidgets.QPushButton(Dialog)
        self.btn_4.setObjectName("btn_4")
        self.horizontalLayout.addWidget(self.btn_4)
        self.btn_3 = QtWidgets.QPushButton(Dialog)
        self.btn_3.setObjectName("btn_3")
        self.horizontalLayout.addWidget(self.btn_3)
        self.btn_2 = QtWidgets.QPushButton(Dialog)
        self.btn_2.setObjectName("btn_2")
        self.horizontalLayout.addWidget(self.btn_2)
        self.btn_entry = QtWidgets.QPushButton(Dialog)
        self.btn_entry.setObjectName("btn_entry")
        self.horizontalLayout.addWidget(self.btn_entry)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.plotWindow = QtWidgets.QWidget(Dialog)
        self.plotWindow.setObjectName("plotWindow")
        self.plotLayout = QtWidgets.QVBoxLayout(self.plotWindow)
        self.plotLayout.setObjectName("plotLayout")
        self.verticalLayout.addWidget(self.plotWindow)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btn_5.setText(_translate("Dialog", "5"))
        self.btn_5.setShortcut(_translate("Dialog", "5"))
        self.btn_4.setText(_translate("Dialog", "4"))
        self.btn_4.setShortcut(_translate("Dialog", "4"))
        self.btn_3.setText(_translate("Dialog", "3"))
        self.btn_3.setShortcut(_translate("Dialog", "3"))
        self.btn_2.setText(_translate("Dialog", "2"))
        self.btn_2.setShortcut(_translate("Dialog", "2"))
        self.btn_entry.setText(_translate("Dialog", "Enter"))
